# Generated by Django 4.1.3 on 2023-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_tuition_alter_student_id_delete_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='stage',
            field=models.CharField(choices=[('1', 'First Stage'), ('2', 'Second Stage'), ('3', 'Third Stage')], default='default_value', max_length=1, null=True),
        ),
    ]
