# Generated by Django 4.1.3 on 2023-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='stage',
            field=models.CharField(choices=[('', 'اختار الصف التعليمي'), ('BC', 'مرحلة تمهيدي'), ('KG1', 'رياض أطفال 1'), ('KG2', 'رياض أطفال 2'), ('Prim1', 'الصف الأول الابتدائي- Grade 1'), ('Prim2', 'الصف الثاني الابتدائي- Grade 2'), ('Prim3', 'الصف الثالث الابتدائي- Grade 3'), ('Prim4', 'الصف الرابع الابتدائي- Grade 4'), ('Prim5', 'الصف الخامس الابتدائي- Grade 5'), ('Prim6', 'الصف السادس الابتدائي- Grade 6'), ('Prep7', 'الصف الأول الإعدادي- Grade 7'), ('Prep8', 'الصف الثاني الإعدادي- Grade 8'), ('Prep9', 'الصف الثالث الإعدادي- Grade 9'), ('Sec1', 'الصف الأول الثانويSecondary School 1'), ('Sec2', 'الصف الثاني الثانويSecondary School 2'), ('Sec3', 'الصف الثالث الثانويSecondary School 3')], default='default_value', max_length=50, null=True),
        ),
    ]
