# Generated by Django 4.1.3 on 2023-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_classroom_students_remove_student_classroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='stage',
            field=models.CharField(choices=[('1', 'Primary Stage'), ('2', 'Prep Stage'), ('3', 'Secondary Stage')], default='default_value', max_length=1, null=True),
        ),
    ]
