# Generated by Django 4.1.3 on 2023-05-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_classroom_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_expenses', to='students.classroom'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(default='2023', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='stage',
            field=models.CharField(choices=[('', 'Choose Educational Stage'), ('BC', 'Preparatory Stage'), ('KG1', 'Kindergarten 1'), ('KG2', 'Kindergarten 2'), ('Prim1', 'Grade 1'), ('Prim2', 'Grade 2'), ('Prim3', 'Grade 3'), ('Prim4', 'Grade 4'), ('Prim5', 'Grade 5'), ('Prim6', 'Grade 6'), ('Prep7', 'Grade 7'), ('Prep8', 'Grade 8'), ('Prep9', 'Grade 9'), ('Sec1', 'Secondary School 1'), ('Sec2', 'Secondary School 2'), ('Sec3', 'Secondary School 3')], default='default_value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_expenses', to='students.student'),
        ),
    ]
