# Generated by Django 4.1.3 on 2023-05-16 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_classroom_students_alter_classroom_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='receipt_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tuition',
            name='receipt_number',
            field=models.CharField(default='DEFAULT_RECEIPT_NUMBER', max_length=20),
        ),
    ]
