# Generated by Django 4.1.3 on 2023-05-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_tuition_receipt_date_tuition_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='receipt_number',
        ),
    ]
