# Generated by Django 4.1.3 on 2023-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_classroom_stage_alter_educationalstage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='Default Classroom Name', max_length=100, null=True),
        ),
    ]
