# Generated by Django 4.1.3 on 2023-05-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_tuition_date_remove_tuition_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='students.student'),
        ),
    ]
