# Generated by Django 4.1.3 on 2023-05-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_classroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='student',
        ),
    ]
