# Generated by Django 4.1.3 on 2023-05-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_expense_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition', to='students.classroom'),
        ),
    ]
