# Generated by Django 4.1.3 on 2023-05-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_tuition_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='payer',
        ),
    ]
