# Generated by Django 4.1.3 on 2023-05-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_tuition_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
