# Generated by Django 4.1.3 on 2023-05-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_total_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='fee_per_student',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
