# Generated by Django 4.1.3 on 2023-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_expense_total_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
