# Generated by Django 4.1.3 on 2023-06-14 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_total_owed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='receipt_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
