# Generated by Django 4.1.3 on 2023-06-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_classroom_stage_alter_tuition_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='stage',
            field=models.CharField(choices=[('', 'اختار المرحلة التعليمية'), ('BC', 'مرحلة تمهيدي'), ('KG1', 'رياض أطفال 1'), ('KG2', 'رياض أطفال 2'), ('Prim1', 'الصف الأول الابتدائي'), ('Prim2', 'الصف الثاني الابتدائي'), ('Prim3', 'الصف الثالث الابتدائي'), ('Prim4', 'الصف الرابع الابتدائي'), ('Prim5', 'الصف الخامس الابتدائي'), ('Prim6', 'الصف السادس الابتدائي'), ('Prep7', 'الصف الأول الإعدادي'), ('Prep8', 'الصف الثاني الإعدادي'), ('Prep9', 'الصف الثالث الإعدادي'), ('Sec1', 'الصف الأول الثانوي'), ('Sec2', 'الصف الثاني الثانوي'), ('Sec3', 'الصف الثالث الثانوي')], default='default_value', max_length=50, null=True),
        ),
    ]
