# Generated by Django 4.1.3 on 2023-06-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_classroom_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_by_name', to='students.classroom'),
        ),
    ]
