# Generated by Django 4.1.3 on 2023-06-18 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_student_classroom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('national_number', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('classroom', models.CharField(max_length=50)),
                ('academic_year', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear')),
            ],
        ),
    ]
