# Generated by Django 4.1.3 on 2023-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
