# Generated by Django 4.1.3 on 2023-06-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_tuition_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='payment_date',
        ),
    ]
