# Generated by Django 4.1.3 on 2023-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_remove_tuition_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='payment_user',
            field=models.CharField(default='account user', max_length=50),
        ),
    ]
